---
rails_logrotate_name: '{{ app_name }}'

rails_logrotate_path: '{{ RAILS_APP_LOG_PATH }}'
rails_logrotate_mask: '*.log'

rails_logrotate_options:
- su deploy deploy
- compress
- copytruncate
- daily
- delaycompress
- missingok
- rotate 7
