---
# the default ruby version
rvm_default: "{{ ruby_version }}"

# additional ruby versions
rvm_rubies: []

# user that installs rvm
rvm_user: "{{ deploy_user }}"

# gem version for default ruby (empty means no changes)
gem_version: '2.7.9'
rvm_gem_version: "{{ gem_version }}"

# gpg keys required for rvm installation
rvm_gpg_keys: "7D2BAF1CF37B13E2069D6956105BD0E739499BDB 409B6B1796C275462A1703113804BB82D39DC0E3"
rvm_gpg_key_server: "hkp://pool.sks-keyservers.net" # 'hkp://keys.gnupg.net'
rvm_gpg_key_alternative_url: "https://rvm.io/mpapis.asc"

# additional packages
rvm_custom_packages:
- nodejs # precompile assets

rvm_install_gems:
- bundler
