# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: accef35e9c8eca3bd948b25d2f0a9d96e95e67302ff14405753087fdfe8fd505477d9c8b2d0bf8d973255703636409b6f0e5493ba666ca741ff7c97d4d049c14

test:
  secret_key_base: 506e04ea591ae7f4efeb78b211cc2f59155808f04e457793ed51369320f88b6591526607dbf46736a706dac0e2f6982c34c4461a3dc5599fef7ae1b4543f1646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
